spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aitooldb?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      validation-query: SELECT 1
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  web:
    resources:
      static-locations: classpath:/static/, file:${file-upload.location}/**
ip:
  path: http://localhost:8080


file-upload:
  location: ${user.dir}/upload

mybatis:
  type-aliases-package: org.amm.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


server:
  port: 8080
  servlet:
    session:
      timeout: 1800
      cookie:
        max-age: 1800
    context-path: /AITool
#    session:
#      cookie:
#        name: JSESSIONID
#        path: /
#        http-only: true
#        secure: false